[tool.poetry]
name = "ibkr-trader"
version = "0.1.0"
description = ""
authors = ["barak-kovrr <barako@kovrr.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
